name: wmbusmeters
adopt-info: wmbusmeters
summary: "Program receives and decodes WMBus telegrams"
description: |
  The program receives and decodes C1, T1 or S1 telegrams
  (using the wireless mbus protocol) to acquire utility meter readings.
  The readings can then be published using MQTT, curled to a REST api,
  inserted into a database or stored in a log file.
  Following must be executed "sudo snap connect wmbusmeters:raw-usb core:raw-usb"
  to allow snap read USB devices and check that root user of your system is
  added to group that can read USB devices

base: core18
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: arm64
    run-on: arm64

  - build-on: armhf
    run-on: armhf

parts:
  script:
    plugin: dump
    source: snap/local/
    prime:
      - launcher.sh

  wmbusmeters:
    source: "https://github.com/weetmuts/wmbusmeters.git"
    source-type: git
    override-pull: |
      snapcraftctl pull
      if [ -n "$(git describe --tags | grep -)" ]; then
        GIT_REV="$(git describe --tags | cut -f1,2 -d'-')"
        snapcraftctl set-version "$GIT_REV"
        snapcraftctl set-grade devel
      else
        GIT_VER="$(git describe --tags)"
        snapcraftctl set-version "$GIT_VER"
        snapcraftctl set-grade stable
      fi
    plugin: autotools
    build-packages:
      - g++
      - make
      - librtlsdr-dev
      - libncurses5-dev
    stage-packages:
      - mosquitto-clients
      - curl
      - libusb-1.0-0
      - rtl-sdr
    prime:
      - usr/bin/
      - usr/lib/
      - lib/
      - etc/wmbusmeters.conf

  rtl-wmbus:
    source: "https://github.com/weetmuts/rtl-wmbus.git"
    plugin: make
    artifacts:
      - build/rtl_wmbus
    organize:
      build/rtl_wmbus: usr/bin/rtl_wmbus
    prime:
      - usr/bin/rtl_wmbus

  rtl-433:
    source: "https://github.com/merbanan/rtl_433.git"
    plugin: cmake
    organize:
      bin/rtl_433: usr/bin/rtl_433
    prime:
      - usr/bin/rtl_433

apps:
  wmbusmeters:
    command: /bin/sh $SNAP/launcher.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - raw-usb